version: '3'

build:
  args:
    - backend-repo
    - frontend-repo
    - backend-branch
    - frontend-branch

services:
  nginx:
    build: ./nginx
    restart: always
    depends_on: 
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - frontend-dist:/app/frontend

  frontend:
    build: ./frontend
    volumes:
      - frontend-dist:/app/dist

  backend:
    build: ./backend
    restart: always
    ports: 
      - "5000"
    depends_on:
      - db
      - backend-pwdless
    
  backend-pwdless:
    build: ./backend
      args: 
        - backend-repo = https://github.com/pwdless/pwdless
        - backend-branch = 2.0
    environment:
      - pwdless:stuffs = hello
    restart: always
    ports:
      - "5001"
    depends_on:
      - db
      
  db:
    build: ./postgres
    restart: always
    volumes:
      - /app/pg-vol/data:/var/lib/postgresql/data
      - /app/pg-vol/config:/etc/postgresql
      - /app/pg-vol/logs:/var/log/postgresql

volumes:
  frontend-dist:
